name: BETA

on:
  workflow_dispatch:  # Permite iniciar manualmente
  schedule:
    - cron: '0 18 * * 1-5' # Executa às 18:00 UTC (15:00 BRT) segunda a sexta https://crontab.guru/#0_22_*_*_1-5

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Log workflow dispatch
        run: echo "Workflow dispatched at $(date)"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm and Cypress
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install

      - name: Cypress info and verify
        run: |
          yarn cypress cache path
          yarn cypress cache list
          yarn cypress verify
          yarn cypress info

      - name: Notify Cronitor start
        run: curl -X POST 'https://cronitor.link/p/95228ef28fdb492ca3c80ca7fdac0443/zJRpN1?state=run'

      - name: Run Cypress tests in beta
        run: yarn test:beta
        env:
          CI: true
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        continue-on-error: true

      - name: Archive Cypress test results
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports

      - name: Archive Cypress HTML report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-html-report
          path: cypress/reports/*.html

      - name: Archive screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Archive videos on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Notify Cronitor complete
        if: success()
        run: curl -X POST 'https://cronitor.link/p/95228ef28fdb492ca3c80ca7fdac0443/zJRpN1?state=complete'

      - name: Notify Cronitor failure
        if: failure()
        run: curl -X POST 'https://cronitor.link/p/95228ef28fdb492ca3c80ca7fdac0443/zJRpN1?state=fail'
