name: Cypress Parallel Tests

on:
  push:
    branches-ignore:
      - "renovate/**"

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.12.0-chrome-123.0.6312.86-1-ff-124.0.2-edge-123.0.2420.65-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: List files in workspace
        run: ls -R  # Lista todos os arquivos e diretórios para verificação

  test:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
        viewport: [default, mobile]

    container:
      image: cypress/browsers:node-20.12.0-chrome-123.0.6312.86-1-ff-124.0.2-edge-123.0.2420.65-1
      options: --user 1001
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node info
        run: node -v

      - name: "Run Cypress Tests"
        uses: cypress-io/github-action@v6
        with:
          start: yarn start:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: ${{ matrix.browser }}
          record: true
          parallel: true
          group: "UI - ${{ matrix.browser }}$([[ matrix.viewport == 'mobile' ]] ? ' - Mobile' : '')"
          spec: cypress/tests/ui/*
          config-file: cypress.config.ts
          config: ${{ matrix.viewport == 'mobile' && '{"e2e":{"viewportWidth":375,"viewportHeight":667}}' || '{}' }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
