name: Run Cypress Tests for MODO1, MODO2, MODO3

on:
  workflow_dispatch:  # Permite iniciar manualmente
  schedule:
    - cron: '0 16 * * 1,4' # Executaàs 16:00 UTC (13:00 BRT) segunda e quinta

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode:
          - MODO1
          - MODO2
          - MODO3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: yarn install

      - name: Run Cypress Tests for ${{ matrix.mode }}
        run: yarn spec "cypress/e2e/Cypressjoao/MkWhatsOne/${{ matrix.mode }}.cy.js"
        working-directory: ${{ github.workspace }}

      - name: Upload Cypress Artifacts for ${{ matrix.mode }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts-${{ matrix.mode }}
          path: cypress/screenshots, cypress/videos