name: Cypress 

on:
  push:
    branches:
      - principal
  pull_request:
    branches:
      - principal

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true

      - name: Merge Mochawesome JSON reports
        run: npx mochawesome-merge cypress/reports/*.json -o cypress/reports/mochawesome.json

      - name: Generate Mochawesome HTML report
        run: npx marge cypress/reports/mochawesome.json -o cypress/reports --reportFilename=index

      - name: Archive Cypress test results
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports

      - name: Archive Cypress HTML report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-html-report
          path: cypress/reports/*.html

      - name: Archive screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Archive videos on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Send notification on test failure
        if: failure()
        run: |
          WEBHOOK_URL="https://mkmservicecom.webhook.office.com/webhookb2/a11da518-494e-4b92-ab2e-eae01ec8ff11@6bb1f81b-c7c7-4eec-a417-11ceb617097d/IncomingWebhook/73006ad307184662bfbe7b39dec2a5f3/6707798e-6692-4adb-8ec0-09ea01b9bb94"
          curl -X POST -H "Content-Type: application/json" -d "{
            \"@type\": \"MessageCard\",
            \"@context\": \"http://schema.org/extensions\",
            \"summary\": \"Cypress Test Run Failed\",
            \"themeColor\": \"FF0000\",
            \"sections\": [{
              \"activityTitle\": \"Cypress Test Suite Failure\",
              \"activitySubtitle\": \"A test run has failed. Please check the details below.\",
              \"facts\": [{
                \"name\": \"Repository =>\",
                \"value\": \"${{ github.repository }}\"
              }, {
                \"name\": \"Workflow =>\",
                \"value\": \"${{ github.workflow }}\"
              }, {
                \"name\": \"Branch =>\",
                \"value\": \"${{ github.ref }}\"
              }, {
                \"name\": \"Commit =>\",
                \"value\": \"${{ github.sha }}\"
              }, {
                \"name\": \"Action Details =>\",
                \"value\": \"[View Action Logs](https://github.com/Joao848846/mkm-cypress/actions)\"
              }],
              \"markdown\": true
            }]
          }" $WEBHOOK_URL