name: Cypress

on:
  push:
    branches:
      - principal
  pull_request:
    branches:
      - principal
  schedule:
    # Executa às 18:00 todos os dias da semana de segunda a sexta
    - cron: '0 18 * * 1-5'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Notify Cronitor start
        run: curl -X POST https://cronitor.link/your-monitor-code/run
        env:
          CRONITOR_API_KEY: ${{ secrets.CRONITOR_API_KEY }}

      - name: Run Cypress tests and record
        run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
        env:
          CI: true
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Merge Mochawesome JSON reports
        run: npx mochawesome-merge cypress/reports/*.json -o cypress/reports/mochawesome.json

      - name: Generate Mochawesome HTML report
        run: npx marge cypress/reports/mochawesome.json -o cypress/reports --reportFilename=index

      - name: Archive Cypress test results
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports

      - name: Archive Cypress HTML report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-html-report
          path: cypress/reports/*.html

      - name: Archive screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Archive videos on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Notify Cronitor complete
        if: success()
        run: curl -X POST https://cypress-mkm.cronitorstatus.com/complete
        env:
          CRONITOR_API_KEY: ${{ secrets.CRONITOR_API_KEY }}

      - name: Notify Cronitor failure
        if: failure()
        run: curl -X POST https://cypress-mkm.cronitorstatus.com/fail
        env:
          CRONITOR_API_KEY: ${{ secrets.CRONITOR_API_KEY }}
